alias gits="git status"
alias gitf="git fetch --prune"
alias gitrbm="git rebase master"
alias gitlog="git log --abbrev-commit --format=oneline -n 7"
alias gitmast="git checkout master"
alias gd="git diff --stat master HEAD"
alias gdf="git diff master HEAD"
alias h="git diff HEAD -w --ignore-blank-lines --cached"
alias recent="git for-each-ref --sort=-committerdate --format='%(committerdate:short) %(color:yellow)%(refname:short)%(color:reset)' refs/heads"
alias wip="git commit -m \"wip\" && git status"
alias sdir="find . -print | sed -e \"s;[^/]*/;|___;g;s;___|; |;g\""
alias dcupb="docker compose up --build"
alias dcup="docker compose up --remove-orphans"
alias dcst="docker compose down"
alias randkeys="for i in {1..24}; do openssl rand -base64 48; done"
alias wttr="curl http://wttr.in/Simferopol"
alias gof="go fmt ./..."
